### ISSUE TITLE
Correción

### ISSUE THREAD

**Issue by ango1994** [RafGarLo/202210-w3-d3-rafael.garcia#6]
Buenas Rafael! No dejes carpetas viejas en tu repositorio. Si no tienen ningún uso en tu aplicación no deberían estar ahí. En cuanto al ejercicio está muy bien. Procura quitarle el margen al body para que no se vean esas esquinas blancas. Procura también hacer más commits y no trabajar en la misma rama después de haber hecho una pull request. No está mal de por sí, pero vamos a procurar trabajar cerrando las ramas una vez hemos hecho la pull request y las hayamos mergeado. Ánimo! 💪

**Comment by RafGarLo** [comment]
Gracias! Tomo nota.
